"""add IMD warning fields to alerts

Revision ID: 0332ff82c89e
Revises: fb782ac06a4c
Create Date: 2026-09-03 23:51:04.340295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0332ff82c89e'
down_revision: Union[str, Sequence[str], None] = 'fb782ac06a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('forecast_date', sa.Date(), nullable=False))
    op.add_column('alerts', sa.Column('warning_code', sa.Integer(), nullable=False))
    op.add_column('alerts', sa.Column('warning_color', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_alerts_forecast_date'), 'alerts', ['forecast_date'], unique=False)
    op.create_unique_constraint('uq_alert_location_source_date_code_color', 'alerts', ['location_id', 'source', 'forecast_date', 'warning_code', 'warning_color'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_alert_location_source_date_code_color', 'alerts', type_='unique')
    op.drop_index(op.f('ix_alerts_forecast_date'), table_name='alerts')
    op.drop_column('alerts', 'warning_color')
    op.drop_column('alerts', 'warning_code')
    op.drop_column('alerts', 'forecast_date')
    # ### end Alembic commands ###
