"""create daily forecast table

Revision ID: b39d25f4ae4f
Revises: e76004669a8b
Create Date: 2026-09-03 23:14:35.747974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b39d25f4ae4f'
down_revision: Union[str, Sequence[str], None] = 'e76004669a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('temperature_max', sa.Float(), nullable=True),
    sa.Column('temperature_min', sa.Float(), nullable=True),
    sa.Column('feels_like_max', sa.Float(), nullable=True),
    sa.Column('feels_like_min', sa.Float(), nullable=True),
    sa.Column('precipitation_sum', sa.Float(), nullable=True),
    sa.Column('rain_sum', sa.Float(), nullable=True),
    sa.Column('precipitation_probability_max', sa.Float(), nullable=True),
    sa.Column('precipitation_hours', sa.Float(), nullable=True),
    sa.Column('wind_speed_max', sa.Float(), nullable=True),
    sa.Column('wind_gusts_max', sa.Float(), nullable=True),
    sa.Column('wind_direction_dominant', sa.Float(), nullable=True),
    sa.Column('sunrise', sa.DateTime(), nullable=True),
    sa.Column('sunset', sa.DateTime(), nullable=True),
    sa.Column('weather_condition', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_forecasts_forecast_date'), 'daily_forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_daily_forecasts_id'), 'daily_forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_daily_forecasts_location_id'), 'daily_forecasts', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_forecasts_location_id'), table_name='daily_forecasts')
    op.drop_index(op.f('ix_daily_forecasts_id'), table_name='daily_forecasts')
    op.drop_index(op.f('ix_daily_forecasts_forecast_date'), table_name='daily_forecasts')
    op.drop_table('daily_forecasts')
    # ### end Alembic commands ###
