"""add forecast uniqueness constraints

Revision ID: fb782ac06a4c
Revises: b39d25f4ae4f
Create Date: 2026-09-03 23:34:30.736873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb782ac06a4c'
down_revision: Union[str, Sequence[str], None] = 'b39d25f4ae4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_daily_forecast_location_date_source', 'daily_forecasts', ['location_id', 'forecast_date', 'source'])
    op.create_unique_constraint('uq_forecast_location_time_source', 'forecasts', ['location_id', 'forecast_time', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_forecast_location_time_source', 'forecasts', type_='unique')
    op.drop_constraint('uq_daily_forecast_location_date_source', 'daily_forecasts', type_='unique')
    # ### end Alembic commands ###
